### PR TITLE
Experiment about using generics to catch version mismatches

### PR DESCRIPTION
**Pull request by ftomassetti**
This is an incomplete experiment to check what it means to use generics to catch version mismatches, using a "version token type", as proposed by @enikao .

To make this work, more work should be put in.

Most classes will need to be touched and I am not 100% sure we can make the generics always work.

### CODE REVIEW

**Comment by dslmeinte** [comment]
One question: is it possible, with this approach, to introspect on the version at runtime? I see a `LionWebVersionToken` that has that info. btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)

**Comment by ftomassetti** [comment]
> One question: is it possible, with this approach, to introspect on the version at runtime? I see a `LionWebVersionToken` that has that info. btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)

Yes, but that means we need to both specify the type parameter and pass a value to the constructor

**Comment by ftomassetti** [comment]
> btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)

Oh, good. But doesn't that work just with subclasses? Can you show what you had in mind?

**Comment by dslmeinte** [comment]
> > btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)
> 
> Oh, good. But doesn't that work just with subclasses? Can you show what you had in mind?

I'll try and add it to this branch ASAP

**Comment by ftomassetti** [comment]
> > > btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)
> > 
> > 
> > Oh, good. But doesn't that work just with subclasses? Can you show what you had in mind?
> 
> I'll try and add it to this branch ASAP

Hi Meinte, I wanted to check with you if you can estimate when you will have time to look into this (as 2025 is sneaking on us and we are a bit behind with the release of LW Java 2024.1)

**Comment by dslmeinte** [comment]
> > > > btw: It is possible to reflect on type parameters at runtime, despite type erasure! :)
> > > 
> > > 
> > > Oh, good. But doesn't that work just with subclasses? Can you show what you had in mind?
> > 
> > 
> > I'll try and add it to this branch ASAP
> 
> Hi Meinte, I wanted to check with you if you can estimate when you will have time to look into this (as 2025 is sneaking on us and we are a bit behind with the release of LW Java 2024.1)

Sorry: forgot about this (or rather: I didn't put it on some kind of TODO queue) :(

Here's a link: https://stackoverflow.com/questions/1942644/get-generic-type-of-java-util-list
I intended to add an actually representative unit test to `lionweb-java`, but I still have to get around to that.

**Pull request closed without merging**
